set(VCPKG_TARGET_ARCHITECTURE "@Z_VCPKG_TARGET_TRIPLET_ARCH@")
set(VCPKG_CRT_LINKAGE "@crt_linkage@")
set(VCPKG_SYSTEM_NAME "@Z_VCPKG_TARGET_TRIPLET_PLAT@")
set(VCPKG_LIBRARY_LINKAGE "static")
if(@BUILD_SHARED_LIBS@)
  set(VCPKG_LIBRARY_LINKAGE "dynamic")
endif()
if(@VCPKG_USE_SINGLE_CONFIG@)
  set(VCPKG_BUILD_TYPE release)
endif()

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "@CMAKE_TOOLCHAIN_FILE@")

if(VCPKG_SYSTEM_NAME STREQUAL "windows")
  set(VCPKG_LOAD_VCVARS_ENV ON)
endif()

@PER_PORT_CUSTOMIZATION@
